plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.android.zencodegame.demo'
    compileSdk 36

    defaultConfig {
        applicationId "com.zencodegame.android.demo"
        minSdk 24
        targetSdk 36
        versionCode 171
        versionName "1.0.1"
        manifestPlaceholders["app_key"] = ""
        manifestPlaceholders["APP_ID"] = "10035"
        manifestPlaceholders["APP_SECRET"] = ""
        manifestPlaceholders["Google_Client_Id"] = "536019673773-en4onusp7tohrq4blmnmqd4atd714jnm.apps.googleusercontent.com"
        manifestPlaceholders["VKIDClientID"] = ""
        manifestPlaceholders["VKIDClientSecret"] = ""
        manifestPlaceholders["VKIDRedirectHost"] = ""
        manifestPlaceholders["VKIDRedirectScheme"] = ""
    }

    signingConfigs {
        create("release") {
            storeFile = file("/Users/astroboy/workspace/mcgame/zkgame-keystore.jks")
            storePassword = "zkgame2025"
            keyAlias = "zkgame"
            keyPassword = "zkgame2025"
            enableV2Signing=true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // 添加厂商维度
    flavorDimensions += "vendor"
    // 定义不同厂商的构建变体
    productFlavors {
        create("huawei") {
            dimension = "vendor"
            apply plugin: "com.huawei.agconnect"
            // HUAWEI特定的配置
            applicationId = "com.sqrush.merge.huawei"
            versionCode=100
            versionName="1.0.0"
            manifestPlaceholders["app_key"] = ""
            manifestPlaceholders["APP_ID"] = "10031"
            manifestPlaceholders["APP_SECRET"] = "115239063"
            manifestPlaceholders["VKIDClientID"] = "54112794"
            manifestPlaceholders["VKIDClientSecret"] = "SSK3q7ZdKI5WPn7zP2f8"
            manifestPlaceholders["VKIDRedirectHost"] = "vk.ru"
            manifestPlaceholders["VKIDRedirectScheme"] = "vk54112794"
        }
        create("xiaomi") {
            dimension = "vendor"
            // 小米特定的配置
            applicationId = "com.zencodegame.android.demo"
            versionCode=100
            versionName="1.0.0_mitest"
            manifestPlaceholders["app_key"] = ""
            manifestPlaceholders["APP_ID"] = "10035"
            manifestPlaceholders["APP_SECRET"] = ""
            manifestPlaceholders["Google_Client_Id"] = "536019673773-en4onusp7tohrq4blmnmqd4atd714jnm.apps.googleusercontent.com"
            manifestPlaceholders["VKIDClientID"] = "54112794"
            manifestPlaceholders["VKIDClientSecret"] = "SSK3q7ZdKI5WPn7zP2f8"
            manifestPlaceholders["VKIDRedirectHost"] = "vk.ru"
            manifestPlaceholders["VKIDRedirectScheme"] = "vk54112794"
        }
        create("oppo") {
            dimension = "vendor"
            // OPPO特定的配置
            applicationId = "com.zencodegame.android.demo"
            versionCode = 100
            versionName = "1.0.0"
            manifestPlaceholders["app_key"] = "af143bdf65324300bfae1a50d04fa7d0"
            manifestPlaceholders["APP_ID"] = "10035"
            manifestPlaceholders["APP_SECRET"] = "5f50f0930c0e48f7aedf7147606e3c65"
            manifestPlaceholders["Google_Client_Id"] = "536019673773-en4onusp7tohrq4blmnmqd4atd714jnm.apps.googleusercontent.com"
            manifestPlaceholders["VKIDClientID"] = "54112794"
            manifestPlaceholders["VKIDClientSecret"] = "SSK3q7ZdKI5WPn7zP2f8"
            manifestPlaceholders["VKIDRedirectHost"] = "vk.ru"
            manifestPlaceholders["VKIDRedirectScheme"] = "vk54112794"
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material

    //IAP SDK依赖的包
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // Credential Manager 核心库 不接入账号可以添加
    implementation("androidx.credentials:credentials:1.1.0")    // Play Services 支持库（兼容 Android 13 及以下）
    implementation("androidx.credentials:credentials-play-services-auth:1.0.0-alpha09")
    // Google ID SDK（Sign in with Google 专用） 不接入账号可以添加
    implementation("com.google.android.libraries.identity.googleid:googleid:1.1.1")
    //VK账号登录依赖库 不接入账号可以添加
    implementation("com.vk.id:vkid:2.5.1")

//    implementation files('libs/gameiapsdk-xiaomi-release-v1.5.aar')
//    implementation("com.xiaomi.billingclient:billing:1.2.0")
    //构建OPPO渠道包需要的依赖
    "oppoImplementation" files('libs/gameiapsdk-oppo-release-v1.7.aar')
    //构建小米渠道包需要的依赖
    "xiaomiImplementation" files('libs/gameiapsdk-xiaomi-release-v1.7.aar')
    //构建小米渠道包需要的依赖
    "xiaomiImplementation"("com.xiaomi.billingclient:billing:1.2.0")
    //构建Huawei渠道需要依赖的包
    "huaweiImplementation"(files("libs/gameiapsdk-huawei-release-v1.7.aar"))
    "huaweiImplementation"("com.huawei.hms:iap:6.13.0.300")
    "huaweiImplementation"("com.huawei.agconnect:agconnect-core:1.5.2.300")
    "huaweiImplementation"("com.huawei.hms:hwid:5.3.0.302")
    "huaweiImplementation"("com.auth0:jwks-rsa:0.8.2")
    "huaweiImplementation"("io.jsonwebtoken:jjwt:0.9.1")
    "huaweiImplementation"("com.alibaba:fastjson:1.2.60")
    "huaweiImplementation"("com.google.code.gson:gson:2.8.5")

}